import type { PlayerGender } from "@padel/shared";

import type { LiveTournamentState } from "./tournament";

export interface LiveTournamentViewProps {
  tournament: LiveTournamentState;
  viewerBaseUrl: string;
  errorText: string;
  activeRound: LiveTournamentState["rounds"][number] | null;
  displayedRound: LiveTournamentState["rounds"][number] | null;
  sortedRounds: LiveTournamentState["rounds"];
  selectedRoundIndex: number;
  isLastRound: boolean;
  isTournamentCompleted: boolean;
  isEditingCompletedTournament: boolean;
  scoreInputs: Record<string, { scoreA: string; scoreB: string }>;
  playerNameById: Map<string, string>;
  showEditConfirmModal: boolean;
  showLiveOptionsModal: boolean;
  showAdjustCourtsConfirmModal: boolean;
  tournamentNameDraft: string;
  roundsLeft: number;
  estimatedMinutesLeft: number;
  currentCourts: number;
  proposedCourts: number;
  maxCourts: number;
  canAdjustCourts: boolean;
  scoreEntry: {
    matchId: string;
    scoreA: number | null;
    scoreB: number | null;
    undoStack: { scoreA: number | null; scoreB: number | null }[];
  } | null;
  scoreEntryContextLine: string | null;
  scoreEntryCanComplete: boolean;
  scoreEntryPlusDisabledA: boolean;
  scoreEntryPlusDisabledB: boolean;
  savingScore: boolean;
  pendingCompletedEditMatchId: string | null;
  scoreSheetError: string | null;
  focusSubmitMatchId: string | null;
  showAddPendingPlayerModal: boolean;
  pendingPlayerNameDraft: string;
  pendingPlayerGender: PlayerGender | undefined;
  showIntegrateConfirmModal: boolean;
  renamePlayersVisible: boolean;
  renameDrafts: Record<string, string>;
  renameSaving: boolean;
  onOpenRenamePlayers: () => void;
  onCloseRenamePlayers: () => void;
  onChangeRenameDraft: (playerId: string, name: string) => void;
  onSaveRenames: () => void;
  onOpenAddPendingPlayer: () => void;
  onCloseAddPendingPlayer: () => void;
  onChangePendingPlayerName: (value: string) => void;
  onChangePendingPlayerGender: (gender: PlayerGender) => void;
  onSubmitAddPendingPlayer: () => void;
  onOpenIntegrateConfirm: () => void;
  onCloseIntegrateConfirm: () => void;
  onConfirmIntegratePendingPlayers: () => void;
  onChangeTournamentName: (value: string) => void;
  onChangeProposedCourts: (value: number) => void;
  onSaveTournamentName: () => void;
  onBackToList: () => void;
  onViewLeaderboard: () => void;
  onRefresh: () => void;
  onFinishTournament: () => void;
  onOpenEditConfirm: () => void;
  onCloseEditConfirm: () => void;
  onConfirmEditGame: () => void;
  onOpenLiveOptions: () => void;
  onCloseLiveOptions: () => void;
  onOpenAdjustCourtsConfirm: () => void;
  onCloseAdjustCourtsConfirm: () => void;
  onConfirmAdjustCourts: () => void;
  onSaveGameEdits: () => void;
  onOpenScoreEntry: (matchId: string) => void;
  onCloseScoreEntry: () => void;
  onChangeScoreA: (value: number) => void;
  onChangeScoreB: (value: number) => void;
  onUndoScoreEntry: () => void;
  onSaveScoreEntry: () => void;
  onSaveScoreDraft?: () => void;
  onConfirmEditCompletedScore: () => void;
  onCancelEditCompletedScore: () => void;
  onClearScoreSheetError: () => void;
  onSubmitFocusHandled: () => void;
  onUpdateScoreInput: (matchId: string, side: "scoreA" | "scoreB", value: string) => void;
  onPrevRound: () => void;
  onNextRound: () => void;
  onSubmitRoundScores: () => void;
  canGenerateNextRound?: boolean;
  generatingNextRound?: boolean;
  canFinishNight?: boolean;
  onGenerateNextRound?: () => void;
}
