import Link from "next/link";

export default function HomePage() {
  return (
    <main>
      <h1>Padel Tournament Viewer</h1>
      <p>Open a public tournament page with the share token generated by the organizer app.</p>
      <p>
        Example: <Link href="/tournament/demo">/tournament/demo</Link>
      </p>
    </main>
  );
}
